### ISSUE TITLE
Adjust typography default sizes

### ISSUE THREAD

**Issue by fjarrett** [LiftUX/ascension-theme#1]
I'm not 100% sure which Sass variables should be changed, but these are the final results we'd like to see in the theme typography:

- [x] Change the default `font-size` from `0.75rem` to `0.85rem` (it's too small on mobile)
- [x] Change the default `line-height` from `1.6` to `1.8` (the font could use more breathing room)

**Comment by chriswallace** [comment]
This may be a slight duplicate of issue #2 but we'll update these.

**Comment by schrapel** [comment]
@fjarrett I have increased the font size but in my opinion it is still too small for mobile. I think we should use 16px across the board. Currently 14px mobile, 15px tablet, 16px desktop based on the designs and above changes

**Comment by schrapel** [comment]
Since #2 looks better and it already uses 16px at all sizes I've gone ahead and made this the default across the board. 

I'll close this for now but reopen if you believe it needs to be looked at further

**Comment by fjarrett** [comment]
@schrapel There are still a couple areas where the `line-height` is set to `1.6` or `150%`, such as in the widget areas. Ideally the default should be `1.8` everywhere.

**Comment by schrapel** [comment]
@fjarrett sorry there are a lot of variables in this CSS framework. I've changed the `1.6` and `150%` but going through the compiled style.css there are a lot of random things with other line-heights e.g h1,h2,h3,h4,h5,h6 has line-height of 1.4, an entry meta has 3rem. Do you want me to update everything else too?

**Comment by fjarrett** [comment]
@schrapel I wouldn't worry about headings. I'm only concerned about the line height of normal text, which should be `1.8` (or `180%`).

**Comment by schrapel** [comment]
@fjarrett I've gone through the CSS and updated everything related to normal text to 1.8.

**Comment by fjarrett** [comment]
Looks good.
