### ISSUE TITLE
Missing editor stylesheet

### ISSUE THREAD

**Issue by fjarrett** [LiftUX/ascension-theme#15]
There should be an `add_editor_style()` CSS so the user can use the Visual tab in the Editor and see the same styles used on the front-end.

**Comment by chriswallace** [comment]
@schrapel [Here's a good example](https://github.com/ChurchThemes-WP/uplifted-theme/blob/master/assets/sass/editor-style.scss) of the editor stylesheet. This theme will need to include different Sass files than the ones listed in the example, but its a good reference. We just want the typography styles to match the front-end. Nothing else needs to be applied.

**Comment by schrapel** [comment]
@fjarrett I've changed this. I've included a couple of other partials that I think are relevant.

The problem I noticed was that something was affecting the JS to change the height on the iframe which is now resolved. Can you confirm any other problems are resolved?

**Comment by fjarrett** [comment]
Nicely done.
