### ISSUE TITLE
Increase tagline font size on mobile and tablet

### ISSUE THREAD

**Issue by fjarrett** [LiftUX/ascension-theme#16]
The `.site-description` font size is difficult to read on the **small** and **medium** breakpoints.

<img width="240" alt="screen shot 2016-06-13 at 5 42 28 pm" src="https://cloud.githubusercontent.com/assets/522158/16025638/39e0fa02-318e-11e6-8b3a-2b17aa16fb74.png">
<img width="490" alt="screen shot 2016-06-13 at 5 42 14 pm" src="https://cloud.githubusercontent.com/assets/522158/16025637/39e06b14-318e-11e6-97ac-368e1ca068e9.png">

**Comment by schrapel** [comment]
I even think it is difficult to read on desktop. I'd propose to at least try 12px across all devices. Opinions?

**Comment by fjarrett** [comment]
@schrapel I just tried it with 10px as the default, and 12px on desktop, and it looks great. I think 12px may be a little too large on smaller devices.

**Comment by schrapel** [comment]
@fjarrett what do you think about in the footer? Since the `.site-title` is reduced so should the `.site-description`. I also think it's currently too small

**Comment by fjarrett** [comment]
@schrapel Agreed. I think the `.footer-widget-area .site-description` should be `10px` on all devices.

**Comment by chriswallace** [comment]
![makeitso](https://cloud.githubusercontent.com/assets/80830/16050990/6bce9480-3223-11e6-93fb-9aba1b26d20b.gif)
