### ISSUE TITLE
Use consistent link color in widget areas

### ISSUE THREAD

**Issue by fjarrett** [LiftUX/ascension-theme#19]
The link color inside widgets (`#194f6e`) is not consistent with the link color in the main body (`#39baf3`)

In order to cleanly implement #18 we probably need to keep the link color consistent everywhere.

**Comment by schrapel** [comment]
@chriswallace which color do you want to use site wide?

**Comment by chriswallace** [comment]
@schrapel Let's stick with #39baf3.

**Comment by schrapel** [comment]
@chriswallace I already did based on #18

**Comment by chriswallace** [comment]
Cool, let's close this out then.
