### ISSUE TITLE
Text size on Services page does not match other pages on mobile

### ISSUE THREAD

**Issue by fjarrett** [LiftUX/ascension-theme#2]
The text size on mobile for the Services page does not match any of the other pages.

It’s actually better IMO, because it’s larger. See #1.

## Services
<img width="382" alt="screen shot 2016-06-13 at 5 07 00 pm" src="https://cloud.githubusercontent.com/assets/522158/16024802/4e2f1e12-3189-11e6-8454-e398d49b36e3.png">

## Blog Post
<img width="384" alt="screen shot 2016-06-13 at 5 07 12 pm" src="https://cloud.githubusercontent.com/assets/522158/16024801/4e2e9f78-3189-11e6-8957-362f83534564.png">

**Comment by chriswallace** [comment]
I think this may be a Beaver Builder content difference, but we will check the size of text and make sure we match it up for consistency, especially when it looks good like that.

**Comment by schrapel** [comment]
We are now matching what Beaver Builder uses
