### ISSUE TITLE
Social Menu does not appear to be working

### ISSUE THREAD

**Issue by fjarrett** [LiftUX/ascension-theme#23]
The Social Menu location does not appear to working. I added a Custom Link pointing to Twitter but nothing displays on the front-end. How is this supposed to be configured?

<img width="502" alt="screen shot 2016-06-13 at 6 00 50 pm" src="https://cloud.githubusercontent.com/assets/522158/16026007/cb090216-3190-11e6-93d6-50b89067297c.png">

**Comment by schrapel** [comment]
This is inside the code block that needs all sidebars to be active (which I am going to change). Do you see it when all sidebars are active?

Do you see `<div class="social-menu">...</div>` when you view the source code?

**Comment by fjarrett** [comment]
@schrapel Yes, when there are widgets in all four footer areas the Social Menu appears. So you're right, this is indeed related to #21.
