### ISSUE TITLE
Footer sidebar ordering issue on tablet and mobile

### ISSUE THREAD

**Issue by fjarrett** [LiftUX/ascension-theme#24]
On tablet and mobile, the footer sidebar areas display in a bizarre order: 4, 1, 2, 3

<img width="304" alt="screen shot 2016-06-13 at 10 42 57 pm" src="https://cloud.githubusercontent.com/assets/522158/16030581/4725e45a-31b8-11e6-8584-9d7621989154.png">

**Comment by chriswallace** [comment]
That is odd. Will fix.

**Comment by schrapel** [comment]
In the designs the 4th column (site-title, widget area and social) is last on desktop but first on mobile. So I float it to the right on desktop but otherwise it appears first. 

We have a few options

1. Label these widget areas differently instead of sequentially
2. Preserve the order 
3. Use JS to move widget areas or output them twice to show on different screen sizes

Or maybe something else. What do you think?

**Comment by fjarrett** [comment]
@schrapel There aren't any `push` or `pull` grid classes we can leverage for small and medium breakpoints?

**Comment by schrapel** [comment]
@fjarrett looks like there is actually. I didn't look at the grid system but that won't solve the problem

The footer-4 sits between the site-title and social menu that appear at the top of the mobile design

**Comment by fjarrett** [comment]
This footer behavior is seeming more and more odd to me. I'm on the fence about whether I agree with the current implementation.

**Comment by schrapel** [comment]
I am inclined to agree with you on this also

**Comment by fjarrett** [comment]
@schrapel @chriswallace I'd like to propose we get rid of the automagic design stuff here and just treat `footer-4` like all the other footer widget areas. In #21 I've already proposed we move the Social Menu elsewhere, and complications in #23 would also be resolved by doing this. If we really want to put a site title or buttons here we can do so as markup in a Text widget for now.

**Comment by schrapel** [comment]
I am happy with that

**Comment by schrapel** [comment]
This has been changed

**Comment by schrapel** [comment]
@fjarrett I consider #24 #21 #31 complete. If you agree please feel free to close

**Comment by fjarrett** [comment]
Perfect!
