### ISSUE TITLE
Fixed header margin issue on mobile when admin bar is present

### ISSUE THREAD

**Issue by fjarrett** [LiftUX/ascension-theme#25]
When you are logged into WordPress on mobile, with the admin bar present, there is a margin issue with the fixed header when scrolling.

This is unrelated to the background issue in #20.

<img width="384" alt="screen shot 2016-06-13 at 10 46 44 pm" src="https://cloud.githubusercontent.com/assets/522158/16030671/26ff70fa-31b9-11e6-93ae-a4189a1f354d.png">

## Scrolling

<img width="384" alt="screen shot 2016-06-13 at 10 46 54 pm" src="https://cloud.githubusercontent.com/assets/522158/16030670/26fd88ee-31b9-11e6-9dc4-78df8ce3a89a.png">

**Comment by schrapel** [comment]
The fixed header was not a requirement. I have switched to a relative header as it's easier to maintain
