### ISSUE TITLE
Contact send button does not match other styles

### ISSUE THREAD

**Issue by fjarrett** [LiftUX/ascension-theme#26]
I noticed that the **Send** button in the contact form does not match the other button styles in the theme.

<img width="153" alt="screen shot 2016-06-13 at 11 02 26 pm" src="https://cloud.githubusercontent.com/assets/522158/16030855/09d3ae36-31bb-11e6-9a46-214e9b2955ee.png">

**Comment by chriswallace** [comment]
This is styled via Beaver Builder. I'm talking to them now about how we can easily override their default button styles without breaking user customizations.

**Comment by imbradmiller** [comment]
<a href="https:&#x2F;&#x2F;trello.com&#x2F;c&#x2F;rBlEeVxD&#x2F;18-ascension-business-theme"><img src="https:&#x2F;&#x2F;github.trello.services&#x2F;images&#x2F;trello-icon.png" width="12" height="12"> Ascension (Business Theme)</a>
