### ISSUE TITLE
Refactor, add code comment, wordpress coding standards

### ISSUE THREAD

**Issue by schrapel** [LiftUX/ascension-theme#27]

**Comment by chriswallace** [comment]
I added some code comments to functions.php but it's not fully complete just yet. @schrapel Can you finish this up?

**Comment by chriswallace** [comment]
Accidentally pressed the "close and comment button" -_-

**Comment by imbradmiller** [comment]
<a href="https:&#x2F;&#x2F;trello.com&#x2F;c&#x2F;rBlEeVxD&#x2F;18-ascension-business-theme"><img src="https:&#x2F;&#x2F;github.trello.services&#x2F;images&#x2F;trello-icon.png" width="12" height="12"> Ascension (Business Theme)</a>
