### ISSUE TITLE
Layout cannot be changed on a static front page

### ISSUE THREAD

**Issue by fjarrett** [LiftUX/ascension-theme#28]
If you are using a static front page:

<img width="266" alt="screen shot 2016-06-14 at 11 08 25 am" src="https://cloud.githubusercontent.com/assets/522158/16050193/55ff19b6-3220-11e6-8958-11bf7edd914e.png">

When changing layouts inside the Customizer, you _will_ see the static front page change to the layout you select, but it seems that after you Publish the changes and go look at the front-end, it will always display as **2 Columns: Content / Sidebar**.

Note: This does not happen on the **Posts page**, or any other page from what I can tell. The layout changes everywhere except the static front page.

**Comment by schrapel** [comment]
@fjarrett have you changed the layout on the **Home** page to **2 Columns: Content / Sidebar** that takes priority? It works fine on my local install

**Comment by fjarrett** [comment]
@schrapel Yep, you're right I did. Changing that to **Default** fixed the problem. I will have to think through the UX a little bit here with @jonathanbardo to see what we can do to communicate this to the user.

**Comment by schrapel** [comment]
I agree

**Comment by imbradmiller** [comment]
<a href="https:&#x2F;&#x2F;trello.com&#x2F;c&#x2F;rBlEeVxD&#x2F;18-ascension-business-theme"><img src="https:&#x2F;&#x2F;github.trello.services&#x2F;images&#x2F;trello-icon.png" width="12" height="12"> Ascension (Business Theme)</a>
