### ISSUE TITLE
Change featurette headings on Services page

### ISSUE THREAD

**Issue by fjarrett** [LiftUX/ascension-theme#29]
I think we should be using `<h3>` or `<h4>` for featurette headings on the **Services** page. The current implementation uses `<h6>` that don't look like the standard ones (I'm assuming BB is adding some sort of styling here). But also just from a purely semantic perspective I don't think `<h6>` makes as much sense.

<img width="292" alt="screen_shot_2016-06-14_at_3_51_55_pm" src="https://cloud.githubusercontent.com/assets/522158/16059366/50929980-3248-11e6-9564-3b15e704ad89.png">

<img width="247" alt="screen shot 2016-06-14 at 10 28 00 am" src="https://cloud.githubusercontent.com/assets/522158/16059507/ce7e7346-3248-11e6-9988-6cf9b60b5662.png">

**Comment by chriswallace** [comment]
Removed BB styling on these and converted to H3.

**Comment by imbradmiller** [comment]
<a href="https:&#x2F;&#x2F;trello.com&#x2F;c&#x2F;rBlEeVxD&#x2F;18-ascension-business-theme"><img src="https:&#x2F;&#x2F;github.trello.services&#x2F;images&#x2F;trello-icon.png" width="12" height="12"> Ascension (Business Theme)</a>
