### ISSUE TITLE
Nested items not supported in the Primary Menu

### ISSUE THREAD

**Issue by fjarrett** [LiftUX/ascension-theme#3]
Nested items in the Primary Menu don’t show up on the front-end. It should support 3 levels (parent > child > grandchild).

<img width="502" alt="screen shot 2016-06-13 at 5 09 00 pm" src="https://cloud.githubusercontent.com/assets/522158/16024850/8daff8f4-3189-11e6-934d-67191a348e5c.png">

<img width="1092" alt="screen shot 2016-06-13 at 5 09 36 pm" src="https://cloud.githubusercontent.com/assets/522158/16024862/a1143f22-3189-11e6-9fd4-4f2f5db99f91.png">

**Comment by schrapel** [comment]
Please review and let me know your thoughts

**Comment by fjarrett** [comment]
@schrapel I'm seeing nested items "jump" when hovering over them. Appears to be a margin problem on the hover state or something. My menu look like this:

<img width="285" alt="screen shot 2016-06-15 at 12 30 00 am" src="https://cloud.githubusercontent.com/assets/522158/16068998/9467de70-3290-11e6-8caa-e0d6e9dea739.png">

**Comment by schrapel** [comment]
Sorry this was fixed. They were inheriting the border-bottom from the top level on hover

**Comment by fjarrett** [comment]
@schrapel We're going to need some JS magic to handle repositioning when menus go off-screen.

<img width="688" alt="screen shot 2016-06-15 at 2 15 46 pm" src="https://cloud.githubusercontent.com/assets/522158/16094017/da80d4fc-3303-11e6-8b0e-8d4aa880e6bc.png">

**Comment by schrapel** [comment]
I agree. Unless we present them in a different way.

**Comment by fjarrett** [comment]
@schrapel It looks like now sub-menu items no longer highlight on hover.
