### ISSUE TITLE
Theme broken in IE8

### ISSUE THREAD

**Issue by fjarrett** [LiftUX/ascension-theme#30]
@chriswallace Adding this issue per our conversation yesterday.

![ie8](https://cloud.githubusercontent.com/assets/522158/16094158/87bee0e6-3304-11e6-9e3d-bb26000897a1.png)

**Comment by chriswallace** [comment]
Will be adding polyfills to remedy this and at least get the theme to render something fairly accurate.

**Comment by chriswallace** [comment]
This theme now supports IE8... It's a bit slow, thanks to the javascript required to make it all happen, but that is the price we pay for rendering a mobile-first theme design in a super old browser...

**Comment by imbradmiller** [comment]
<a href="https:&#x2F;&#x2F;trello.com&#x2F;c&#x2F;rBlEeVxD&#x2F;18-ascension-business-theme"><img src="https:&#x2F;&#x2F;github.trello.services&#x2F;images&#x2F;trello-icon.png" width="12" height="12"> Ascension (Business Theme)</a>
