### ISSUE TITLE
Move Social Menu location to be just above copyright info in footer

### ISSUE THREAD

**Issue by fjarrett** [LiftUX/ascension-theme#31]
Yesterday @chriswallace and discussed the possibility of removing the **Social Menu** location altogether since we will be offering users our [Contact Widgets](https://wordpress.org/plugins/contact-widgets/) plugin. However, I think we should keep it just in case users don't want to use the plugin they can still have social links easily.

I would prefer if we move it above the copyright info instead of inside footer widget 4:

<img width="401" alt="screen shot 2016-06-15 at 2 26 11 pm" src="https://cloud.githubusercontent.com/assets/522158/16094297/3000bb6c-3305-11e6-8a86-785460c52495.png">

**Comment by fjarrett** [comment]
#21 is related.

**Comment by chriswallace** [comment]
Sounds good to me... This is probably where it will appear for other themes in the set as well.

**Comment by schrapel** [comment]
I've changed this. Let me know what you think

**Comment by fjarrett** [comment]
Works great.

**Comment by imbradmiller** [comment]
<a href="https:&#x2F;&#x2F;trello.com&#x2F;c&#x2F;rBlEeVxD&#x2F;18-ascension-business-theme"><img src="https:&#x2F;&#x2F;github.trello.services&#x2F;images&#x2F;trello-icon.png" width="12" height="12"> Ascension (Business Theme)</a>
