### ISSUE TITLE
Change parent theme and rename function references

### ISSUE THREAD

**Issue by fjarrett** [LiftUX/ascension-theme#32]
@chriswallace We now have an official fork of Basis, called Primer: https://github.com/godaddy/wp-primer-theme

This child theme needs to be updated to inherit its template from `primer` instead of `basis-framework`.

Additionally, all references to Basis functions need to be replaced with Primer equivalents, e.g. `basis_font_switcher()` should become `primer_font_switcher()`.

**Comment by schrapel** [comment]
@chriswallace are you able to make the changes to inherit primer and make sure it's on the staging server? 

I'll handle the functions as part of #27 today

**Comment by fjarrett** [comment]
@schrapel Thanks!

**Comment by chriswallace** [comment]
Should be all contained within ec53837c95da6cf9f04212f9c2546bb6307858b9.

**Comment by imbradmiller** [comment]
<a href="https:&#x2F;&#x2F;trello.com&#x2F;c&#x2F;rBlEeVxD&#x2F;18-ascension-business-theme"><img src="https:&#x2F;&#x2F;github.trello.services&#x2F;images&#x2F;trello-icon.png" width="12" height="12"> Ascension (Business Theme)</a>
