### ISSUE TITLE
Homepage hero text has changed, no longer matches design

### ISSUE THREAD

**Issue by chriswallace** [LiftUX/ascension-theme#33]
@schrapel can you take a look at that and see what happened there?

**Comment by schrapel** [comment]
I needed to style all the elements and by default the text size is not to design. We need to add the class large to the blockquote.

I don't particularly like using this area as a widget area though. It's definitely going to be hard for a user to manage.

**Comment by chriswallace** [comment]
Yeah, we can maybe add a custom widget but I don't want to introduce anything that WordPress.org's review team might reject initially, so that may be something we can add later.

**Comment by imbradmiller** [comment]
<a href="https:&#x2F;&#x2F;trello.com&#x2F;c&#x2F;rBlEeVxD&#x2F;18-ascension-business-theme"><img src="https:&#x2F;&#x2F;github.trello.services&#x2F;images&#x2F;trello-icon.png" width="12" height="12"> Ascension (Business Theme)</a>
