### ISSUE TITLE
Currently-selected and hover menu item does not show underline or change in appearance

### ISSUE THREAD

**Issue by chriswallace** [LiftUX/ascension-theme#34]
We need to add the underline for menu items on hover and when the current page is active.

**Comment by imbradmiller** [comment]
<a href="https:&#x2F;&#x2F;trello.com&#x2F;c&#x2F;rBlEeVxD&#x2F;18-ascension-business-theme"><img src="https:&#x2F;&#x2F;github.trello.services&#x2F;images&#x2F;trello-icon.png" width="12" height="12"> Ascension (Business Theme)</a>
