### ISSUE TITLE
Hero container persists when Header Image is removed

### ISSUE THREAD

**Issue by fjarrett** [LiftUX/ascension-theme#35]
Inside the **Customizer > Header** Image panel, users are able to click a "Hide image" button, which is supposed to remove the header image from their site. However, the `.hero` container persists. This markup needs to be removed or hidden with CSS.

<img width="297" alt="screen_shot_2016-06-22_at_3_55_52_pm" src="https://cloud.githubusercontent.com/assets/522158/16283324/f6511898-3891-11e6-896b-0176879cc4aa.png">

<img width="1115" alt="screen shot 2016-06-22 at 3 55 38 pm" src="https://cloud.githubusercontent.com/assets/522158/16283331/fbdb26be-3891-11e6-9b61-731d632dd19b.png">

**Comment by fjarrett** [comment]
Strangely, once I remove the Header Image once I am unable to add it back again unless I upload a custom one.

**Comment by schrapel** [comment]
@fjarrett Do we want to remove the hero container or apply the primary background color? If there is content in the widget I think we should still show it with a colored background in my opinion. The hero container is used to show the title with a custom header or featured image if it exists.

**Comment by schrapel** [comment]
For the default header I need to add `register_default_headers` but I don't think we should use a default header since it's very unlikely the image will be suitable for all users and also I have no idea if this image from the design is licensed in the way the theme is distributed (I doubt it)

https://codex.wordpress.org/Function_Reference/register_default_headers

**Comment by chriswallace** [comment]
@schrapel All the images we are using are licensed for unlimited commercial usage so that's not a big deal. We could also add a few more generic default headers in there as well.

**Comment by fjarrett** [comment]
1. Yeah since we do rely on the Hero area for the page titles it would probably be better to default to a new Header BG Color setting.

2. I'm not a fan of default header images, and this actually will causes headaches with the way we want to use these. I say we remove the stock image from the theme and have a Header BG Color setting.

**Comment by schrapel** [comment]
@fjarrett I've removed default header images

Do we really need a new color setting? I was going to suggest use the primary color

**Comment by fjarrett** [comment]
@schrapel That works too!

**Comment by schrapel** [comment]
Awesome.

**Comment by imbradmiller** [comment]
<a href="https:&#x2F;&#x2F;trello.com&#x2F;c&#x2F;rBlEeVxD&#x2F;18-ascension-business-theme"><img src="https:&#x2F;&#x2F;github.trello.services&#x2F;images&#x2F;trello-icon.png" width="12" height="12"> Ascension (Business Theme)</a>

**Comment by prajwalchandra** [comment]
Hi,

I am using this theme for one of my websites and it works and looks great. But I have these following issues, apart which everything is fine.

1) The hero image is not mobile friendly and if affecting my website traffic. It displays fine on the desktop, but on mobile, it doesn't display full and takes itself a new dimension. I have a written little content on the hero image. But that shouldn't be a problem I believe as it works fine on Desktop.

2)  Is there any way to remove the header image from the posts page? 

Awaiting your response. Thanks in advance.

Regards,
Prajwal
