### ISSUE TITLE
Header image and layout broken after parent theme updates.

### ISSUE THREAD

**Issue by chriswallace** [LiftUX/ascension-theme#36]
See here: http://lift.d.pr/ass2

You can also see on the demo site: http://s17615.p20.sites.pressdns.com/

**Comment by fjarrett** [comment]
@chriswallace What branches are being auto-deployed to this test site? Master for Primer and master for Ascension?

**Comment by chriswallace** [comment]
@fjarrett It's set to `develop` right now for Ascension and the other child themes.

**Comment by chriswallace** [comment]
This has been fixed in 848b168.

**Comment by imbradmiller** [comment]
<a href="https:&#x2F;&#x2F;trello.com&#x2F;c&#x2F;rBlEeVxD&#x2F;18-ascension-business-theme"><img src="https:&#x2F;&#x2F;github.trello.services&#x2F;images&#x2F;trello-icon.png" width="12" height="12"> Ascension (Business Theme)</a>
