### ISSUE TITLE
Apply correct filtering for custom color schemes.

### ISSUE THREAD

**Issue by chriswallace** [LiftUX/ascension-theme#37]
You can see an example here: http://lift.d.pr/xit

Need to change this so the entire header is affected by menu background color change.

**Comment by fjarrett** [comment]
@chriswallace The issue is actually broader than this. Ascension has not yet been integrated with any of the new Primer filters, so right now it's just inheriting the defaults.

See my explanation of how Child Themes should use these filters in https://github.com/LiftUX/activation-theme/issues/3#issuecomment-235673651.

**Comment by chriswallace** [comment]
@fjarrett Thanks for clarifying, I haven't brought myself up to speed on the new format used here. Just identified the issue I saw during QA. Will make sure we're all using these filters appropriately here.

**Comment by fjarrett** [comment]
I'm actually working on a automated way of scraping for targets in https://github.com/godaddy/wp-primer-theme/issues/45 so that `css` doesn't have to be defined for every theme. It will save a boat-load of time. Will report back here when that is completed.

**Comment by fjarrett** [comment]
I had to close https://github.com/godaddy/wp-primer-theme/issues/45. Too many edge cases to account for. We will still need to manually enter CSS targets for each color area into the `primer_color` filter.

**Comment by imbradmiller** [comment]
<a href="https:&#x2F;&#x2F;trello.com&#x2F;c&#x2F;rBlEeVxD&#x2F;18-ascension-business-theme"><img src="https:&#x2F;&#x2F;github.trello.services&#x2F;images&#x2F;trello-icon.png" width="12" height="12"> Ascension (Business Theme)</a>
