### ISSUE TITLE
Nested items in the Primary Menu break styles on mobile

### ISSUE THREAD

**Issue by fjarrett** [LiftUX/ascension-theme#4]
<img width="387" alt="screen shot 2016-06-13 at 5 10 23 pm" src="https://cloud.githubusercontent.com/assets/522158/16024883/c228f338-3189-11e6-9886-3202d1bb04af.png">

**Comment by schrapel** [comment]
I've changed these to match the new designs. I'm not sure whether click to open on mobile is the best for the user experience since you're unable to navigate to links that have children as it will always toggle the children elements. Do you have a better suggestion?

**Comment by fjarrett** [comment]
Yeah good point. I think the design looks nice, but you're right, we need a solution for being able to click the parent item. Could use some direction from @chriswallace on this one.

**Comment by chriswallace** [comment]
The design paradigm I've always preferred is to have a drop-down toggle button for each menu item that has children. [This example](http://demos.upthemes.com/gallery/) offers an ideal picture of what should happen when you have drop-downs on mobile.

**Comment by chriswallace** [comment]
@schrapel How difficult would it be to add something like that to toggle the sub-menus at the top level?
