### ISSUE TITLE
Adjust default <h1> styles

### ISSUE THREAD

**Issue by fjarrett** [LiftUX/ascension-theme#5]
The styles for plain `<h1>` elements (without a class) don’t really seem to match the other headings. Looks too large relative to the others, and could possibly look better without the bold weight?

<img width="303" alt="screen shot 2016-06-13 at 5 11 41 pm" src="https://cloud.githubusercontent.com/assets/522158/16024913/f1492034-3189-11e6-9003-537cfb7018a3.png">

**Comment by chriswallace** [comment]
I think the size is probably ok, maybe decrease it a small amount, but definitely need to make it a lighter weight. Agreed there.

**Comment by schrapel** [comment]
I've reduced the font-size by 6px and set the font-weight to lighter. What do both think?

**Comment by fjarrett** [comment]
@schrapel I think it looks fantastic now.

<img width="247" alt="screen shot 2016-06-14 at 10 28 00 am" src="https://cloud.githubusercontent.com/assets/522158/16048711/b589c86e-321a-11e6-95be-280c03863a33.png">
