### ISSUE TITLE
Adjust font size on post/page titles

### ISSUE THREAD

**Issue by fjarrett** [LiftUX/ascension-theme#6]
The styles for `<h1 class="entry-title">` elements are identical to plain `<h2>` elements. I think it might be good to make the font size a little larger on the post/page titles? (e.g. `2.5rem`)

<img width="668" alt="screen shot 2016-06-13 at 5 16 08 pm" src="https://cloud.githubusercontent.com/assets/522158/16025012/8904ef84-318a-11e6-9e86-03f372287e05.png">

**Comment by chriswallace** [comment]
Agreed, let's do that for single post/page titles.
