### ISSUE TITLE
The <legend> element is missing styles

### ISSUE THREAD

**Issue by fjarrett** [LiftUX/ascension-theme#7]
<img width="783" alt="screen shot 2016-06-13 at 5 16 59 pm" src="https://cloud.githubusercontent.com/assets/522158/16025035/a8f5aad6-318a-11e6-98cf-80590c93b213.png">

**Comment by chriswallace** [comment]
THAT LOOKS AMAZING.

**Comment by schrapel** [comment]
I am not a designer but hopefully this looks good. If not lets get some input from a designer. What do you think?

<img width="732" alt="screenshot 2016-06-13 21 18 02" src="https://cloud.githubusercontent.com/assets/3613405/16028341/6b762e3e-31ac-11e6-8cf8-530e4895e5fb.png">

**Comment by fjarrett** [comment]
@schrapel I think YOU are the legend. Looks great.
