### ISSUE TITLE
Styles missing for several required HTML classes

### ISSUE THREAD

**Issue by fjarrett** [LiftUX/ascension-theme#9]
- [x] `.sticky`
- [x] `.bypostauthor`

**Comment by schrapel** [comment]
I'm waiting on design input on these two

**Comment by chriswallace** [comment]
Let's just add a "sticky" icon when the post is sticky, like so:

![sticky](https://cloud.githubusercontent.com/assets/80830/16099703/512308da-331f-11e6-99ce-edcb9c799d9e.png)

Post author comment design coming in a sec...

**Comment by chriswallace** [comment]
Let's add a simple border around author comments. I don't want to add "author" or any words to it as that then requires translations to be added. For mobile, kill the left/right border width.

<img width="760" alt="post-author" src="https://cloud.githubusercontent.com/assets/80830/16100096/a2090c66-3321-11e6-909b-2048b75a3daa.png">

**Comment by chriswallace** [comment]
The border is the accent color at 20% opacity.
